//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConfigurator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:2502/OEE")]
        public string AdresWCF {
            get {
                return ((string)(this["AdresWCF"]));
            }
            set {
                this["AdresWCF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string RefreshDataFastMiliSecound {
            get {
                return ((string)(this["RefreshDataFastMiliSecound"]));
            }
            set {
                this["RefreshDataFastMiliSecound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string RefreshDataSlowMiliSecound {
            get {
                return ((string)(this["RefreshDataSlowMiliSecound"]));
            }
            set {
                this["RefreshDataSlowMiliSecound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string Shift1Hour {
            get {
                return ((string)(this["Shift1Hour"]));
            }
            set {
                this["Shift1Hour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string Shift2Hour {
            get {
                return ((string)(this["Shift2Hour"]));
            }
            set {
                this["Shift2Hour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public string Shift3Hour {
            get {
                return ((string)(this["Shift3Hour"]));
            }
            set {
                this["Shift3Hour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rez1 {
            get {
                return ((string)(this["rez1"]));
            }
            set {
                this["rez1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string ColorBack1 {
            get {
                return ((string)(this["ColorBack1"]));
            }
            set {
                this["ColorBack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF6E6B6B")]
        public string ColorBack2 {
            get {
                return ((string)(this["ColorBack2"]));
            }
            set {
                this["ColorBack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEFF3F4")]
        public string ColorHeader1 {
            get {
                return ((string)(this["ColorHeader1"]));
            }
            set {
                this["ColorHeader1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF555555")]
        public string ColorHeader2 {
            get {
                return ((string)(this["ColorHeader2"]));
            }
            set {
                this["ColorHeader2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFEFF3F4")]
        public string ColorPanel1 {
            get {
                return ((string)(this["ColorPanel1"]));
            }
            set {
                this["ColorPanel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorPanel2 {
            get {
                return ((string)(this["ColorPanel2"]));
            }
            set {
                this["ColorPanel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF94273B")]
        public string ColorLimitLow1 {
            get {
                return ((string)(this["ColorLimitLow1"]));
            }
            set {
                this["ColorLimitLow1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorLimitLow2 {
            get {
                return ((string)(this["ColorLimitLow2"]));
            }
            set {
                this["ColorLimitLow2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public string ColorLimitMid1 {
            get {
                return ((string)(this["ColorLimitMid1"]));
            }
            set {
                this["ColorLimitMid1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string ColorLimitMid2 {
            get {
                return ((string)(this["ColorLimitMid2"]));
            }
            set {
                this["ColorLimitMid2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF39B882")]
        public string ColorLimitHigh1 {
            get {
                return ((string)(this["ColorLimitHigh1"]));
            }
            set {
                this["ColorLimitHigh1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorLimitHigh2 {
            get {
                return ((string)(this["ColorLimitHigh2"]));
            }
            set {
                this["ColorLimitHigh2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public string ColorGaugeBack1 {
            get {
                return ((string)(this["ColorGaugeBack1"]));
            }
            set {
                this["ColorGaugeBack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorGaugeBack2 {
            get {
                return ((string)(this["ColorGaugeBack2"]));
            }
            set {
                this["ColorGaugeBack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999999")]
        public string ColorGaugeEmptyFill {
            get {
                return ((string)(this["ColorGaugeEmptyFill"]));
            }
            set {
                this["ColorGaugeEmptyFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999999")]
        public string ColorGaugeThick {
            get {
                return ((string)(this["ColorGaugeThick"]));
            }
            set {
                this["ColorGaugeThick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string Range1ProgresBar {
            get {
                return ((string)(this["Range1ProgresBar"]));
            }
            set {
                this["Range1ProgresBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string Range1Gauge {
            get {
                return ((string)(this["Range1Gauge"]));
            }
            set {
                this["Range1Gauge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string Range2Gauge {
            get {
                return ((string)(this["Range2Gauge"]));
            }
            set {
                this["Range2Gauge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public string ColorFontHeader1 {
            get {
                return ((string)(this["ColorFontHeader1"]));
            }
            set {
                this["ColorFontHeader1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string ColorFontBack1 {
            get {
                return ((string)(this["ColorFontBack1"]));
            }
            set {
                this["ColorFontBack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logo_Elektrolux.png")]
        public string LogoLeftFileName {
            get {
                return ((string)(this["LogoLeftFileName"]));
            }
            set {
                this["LogoLeftFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logo_Amister.png")]
        public string LogoRightFileName {
            get {
                return ((string)(this["LogoRightFileName"]));
            }
            set {
                this["LogoRightFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorFontBack2 {
            get {
                return ((string)(this["ColorFontBack2"]));
            }
            set {
                this["ColorFontBack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorFontHeader2 {
            get {
                return ((string)(this["ColorFontHeader2"]));
            }
            set {
                this["ColorFontHeader2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string StartAreaIndex {
            get {
                return ((string)(this["StartAreaIndex"]));
            }
            set {
                this["StartAreaIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string StartMachineIndex {
            get {
                return ((string)(this["StartMachineIndex"]));
            }
            set {
                this["StartMachineIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF999999")]
        public string ColorProgressEmptyFill {
            get {
                return ((string)(this["ColorProgressEmptyFill"]));
            }
            set {
                this["ColorProgressEmptyFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF39B882")]
        public string ColorProgressFill {
            get {
                return ((string)(this["ColorProgressFill"]));
            }
            set {
                this["ColorProgressFill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string MinDurationErrorSecound {
            get {
                return ((string)(this["MinDurationErrorSecound"]));
            }
            set {
                this["MinDurationErrorSecound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ShowParameters {
            get {
                return ((string)(this["ShowParameters"]));
            }
            set {
                this["ShowParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string DataFromDataBase {
            get {
                return ((string)(this["DataFromDataBase"]));
            }
            set {
                this["DataFromDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\MININT-URHGSST\\OEEscreens")]
        public string PathToScreenShot {
            get {
                return ((string)(this["PathToScreenShot"]));
            }
            set {
                this["PathToScreenShot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string CountParamPoints {
            get {
                return ((string)(this["CountParamPoints"]));
            }
            set {
                this["CountParamPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ShowHourSummary {
            get {
                return ((string)(this["ShowHourSummary"]));
            }
            set {
                this["ShowHourSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ShowMicroBreaksChart {
            get {
                return ((string)(this["ShowMicroBreaksChart"]));
            }
            set {
                this["ShowMicroBreaksChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ShowModels {
            get {
                return ((string)(this["ShowModels"]));
            }
            set {
                this["ShowModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string RotateMachines {
            get {
                return ((string)(this["RotateMachines"]));
            }
            set {
                this["RotateMachines"] = value;
            }
        }
    }
}
